/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./../components/ActionBar.vue')['default']
    ActionButton: typeof import('./../components/ui/ActionButton.vue')['default']
    Dialog: typeof import('./../components/ui/Dialog.vue')['default']
    Dropdown: typeof import('./../components/dropdown/Dropdown.vue')['default']
    DropdownItem: typeof import('./../components/dropdown/DropdownItem.vue')['default']
    DropZone: typeof import('./../components/DropZone.vue')['default']
    Editor: typeof import('./../components/Editor/index.vue')['default']
    EditorResult: typeof import('./../components/EditorResult.vue')['default']
    EditorSource: typeof import('./../components/EditorSource.vue')['default']
    IconButton: typeof import('./../components/ui/IconButton.vue')['default']
    InputNumber: typeof import('./../components/ui/InputNumber.vue')['default']
    LanguageSelect: typeof import('./../components/navbar/LanguageSelect.vue')['default']
    LogPanel: typeof import('./../components/LogPanel.vue')['default']
    Modal: typeof import('./../components/ui/Modal.vue')['default']
    MoreAction: typeof import('./../components/navbar/MoreAction.vue')['default']
    Navbar: typeof import('./../components/navbar/index.vue')['default']
    OptionItem: typeof import('./../components/ui/OptionItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/ui/Select.vue')['default']
    Switch: typeof import('./../components/ui/Switch.vue')['default']
  }
}
