/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dropdown: typeof import('./../components/dropdown/Dropdown.vue')['default']
    DropdownItem: typeof import('./../components/dropdown/DropdownItem.vue')['default']
    Editor: typeof import('./../components/Editor/index.vue')['default']
    EditorBase: typeof import('./../components/EditorBase.vue')['default']
    EditorResult: typeof import('./../components/EditorResult.vue')['default']
    EditorSource: typeof import('./../components/EditorSource.vue')['default']
    LanguageSelect: typeof import('./../components/LanguageSelect.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    ResultView: typeof import('./../components/ResultView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
