/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./../components/ActionBar.vue')['default']
    Dropdown: typeof import('./../components/dropdown/Dropdown.vue')['default']
    DropdownItem: typeof import('./../components/dropdown/DropdownItem.vue')['default']
    Editor: typeof import('./../components/Editor/index.vue')['default']
    EditorResult: typeof import('./../components/EditorResult.vue')['default']
    EditorSource: typeof import('./../components/EditorSource.vue')['default']
    InputNumber: typeof import('./../components/ui/InputNumber.vue')['default']
    LanguageSelect: typeof import('./../components/LanguageSelect.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    OptionItem: typeof import('./../components/ui/OptionItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/ui/Select.vue')['default']
    Switch: typeof import('./../components/ui/Switch.vue')['default']
  }
}
